import { FunctionComponent } from "react";
import { Modal } from "@/components/Modal/Modal";
import LoginRegistration from "@/components/LoginRegistration/LoginRegistration";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Next14 Pizza | вход / регистрация",
  description: "Generated by create next app",
};
interface ProductIdProps {
  params: { id: string };
  searchParams: { [key: string]: string | string[] | undefined };
}

const ProductId: FunctionComponent<ProductIdProps> = async ({
  params,
  searchParams,
}) => {
  
  return (
    <>
      <Modal>
      <LoginRegistration></LoginRegistration>
        {/* <div>modal карточка продукта {params.id}</div>
        <pre>{JSON.stringify(product, null, 2)}</pre> */}
      </Modal>
    </>
  );
};

export default ProductId;
