import Container from "@/components/Container/Container";
import Header from "@/components/Header/Header";
import { Metadata } from "next";
import { FunctionComponent } from "react";
export const metadata: Metadata = {
  title: "Next14 Pizza | оформление заказа",
  description: "Generated by create next app",
};
interface BuyOrderLayoutProps {
  children: React.ReactNode;
}

const BuyOrderLayout: FunctionComponent<BuyOrderLayoutProps> = ({
  children,
}) => {
  return (
    <>
      <main
        className={" h-screen  bg-[hsla(20,100%,88%,1)]"}
      >
        <Header
          headerSeach={false}
          headerCart={false}
          className="border-white"
        ></Header>
        <Container>
          {children}
        </Container>
      </main>
      <div className="modalwind relative z-20" id="modal_container"></div>
    </>
  );
};

export default BuyOrderLayout;
