import LoginRegistration from "@/components/LoginRegistration/LoginRegistration";
import { Title } from "@/components/Title/Title";
import { Metadata } from "next";
import { FunctionComponent } from "react";
export const metadata: Metadata = {
  title: "Next14 Pizza | профиль ",
  description: "Generated by create next app",
};
interface ProfilePageProps {}

const ProfilePage: FunctionComponent<ProfilePageProps> = async() => {
  return (
    <>
          <div className="w-[800px] max-w-[100%] mx-auto my-7 p-5 text-center">
    <Title>Профиль</Title>
    </div>
  
      
      {/* <LoginRegistration></LoginRegistration> */}
    </>
  );
};

export default ProfilePage;
