import LoginRegistration from "@/components/LoginRegistration/LoginRegistration";
import { Title } from "@/components/Title/Title";
import { Metadata } from "next";
import { FunctionComponent } from "react";
export const metadata: Metadata = {
  title: "Next14 Pizza | профиль ",
  description: "Generated by create next app",
};
import { isAuth } from "@/../services/serverAction";
import { redirect } from "next/navigation";
import { cookies, headers } from "next/headers";
// export const revalidate = 0;
// export const dynamic = 'force-dynamic';
// import { unstable_noStore as noStore } from 'next/cache';
interface ProfilePageProps {}

const ProfilePage: FunctionComponent<ProfilePageProps> = async() => {
  // const cookiesList = cookies();
  const headersList = headers();
  const Auth = await  isAuth()
  console.log("Auth", Auth);
  // noStore();
  if (!Auth) {
    redirect("/auth");
  }
  return (
    <>
          <div className="w-[800px] max-w-[100%] mx-auto my-7 p-5 text-center">
    <Title>Профиль</Title>
    </div>
  
      
      {/* <LoginRegistration></LoginRegistration> */}
    </>
  );
};

export default ProfilePage;
