import { Metadata } from "next";
import Container from "@/components/Container/Container";
import Profile from "@/components/Profile/Profile";
import { Suspense } from "react";
import dynamic from "next/dynamic";

const DynamicProfile = dynamic(
  () =>
    import("@/components/Profile/Profile")
      .catch((error) => {
        return () => <div>ошибка {error.message}</div>;
      }),
  {
    ssr: false,
    loading: () => null,
  }
);

export const metadata: Metadata = {
  title: "Next14 Pizza | профиль ",
  description: "Generated by create next app",
};


const ProfilePage = async () => {
  return (
    <Container>
      {/* <Suspense fallback={<div>Loading...</div>}> */}
        {/* <Profile /> */}
        <DynamicProfile />
      {/* </Suspense> */}
    </Container>
  );
};

export default ProfilePage;
