import type { Metadata } from "next";
import Header from "@/components/Header/Header";
// import { cookies } from "next/headers";
// import { verifyTokenJWB } from "@/lib/utils";

// export const dynamic = 'force-dynamic';
// export const revalidate = 0;

export const metadata: Metadata = {
  title: "Next14 Pizza | главная",
  description: "Generated by create next app",
};

export default function MainLayout(
  {
    children,
    modal,
  }: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
  }>,
  ...props: any
) {

  return (
    <>
      <Header ></Header>
      <main // className={"min-h-screen"} 
      >
        {children}
      </main>
      {modal != null && <div className="modalwind relative z-20">{modal}</div>}
    </>
  );
}
