import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next14 Pizza | оплата",
  description: "Generated by create next app",
};

export default function FakePayLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <main 
      >
        {children}
      </main>
    </>
  );
}