import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import CheckAuth, { RouteGuard } from "@/components/CheckAuth/CheckAuth";

// import '../middleware.ts';
const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Next14 Pizza | главная",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CheckAuth />
      {/* <RouteGuard/> */}
      <body
        className={
          nunito.className
          // + ' scrl_glbl'
        }
      >
        {/* <pre>{JSON.stringify(user, null, 2)}</pre> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
