import LoginRegistration from "@/components/LoginRegistration/LoginRegistration";
import { Title } from "@/components/Title/Title";
import { Metadata } from "next";
import { FunctionComponent } from "react";
export const metadata: Metadata = {
  title: "Next14 Pizza | вход / регистрация",
  description: "Generated by create next app",
};
interface AuthPageProps {}

const AuthPage: FunctionComponent<AuthPageProps> = async() => {
  return (
    <>
    <div className="w-[800px] max-w-[100%] mx-auto my-7 p-5 text-center">
    <Title>Вы были перенаправлены на эту страницу, так как не авторизованы и/или не имели доступа.
        Авторизуйтесь и попробуйте заново.</Title>
    </div>
  
      
      <LoginRegistration></LoginRegistration>
    </>
  );
};

export default AuthPage;