import { Metadata } from "next";
import { FunctionComponent } from "react";
export const metadata: Metadata = {
  title: "Next14 Pizza | оформление заказа",
  description: "Generated by create next app",
};
interface BuyOrderLayoutProps {
  children: React.ReactNode;
  modalAuth: React.ReactNode;
}

const BuyOrderCartLayout: FunctionComponent<BuyOrderLayoutProps> = ({
  children,
  modalAuth,
}) => {
  return (
    <>
      {children}
      {modalAuth != null && (
        <div 
        className="modalwind relative z-20" 
        style={{ display: "none" }}
        id="layout_modal_container"
        >
          {modalAuth}
        </div>
      )}
    </>
  );
};
 
export default BuyOrderCartLayout;
