import type { Metadata } from "next";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Next14 Pizza | Вход",
  description: "Generated by create next app",
};

export default function LogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>,...props: any) {

  return (
    <>
      <Header headerSeach={false} headerLogin={false}></Header>
      <main // className={"min-h-screen"}
      >
        {children}
      </main>
    </>
  );
}