import { FunctionComponent } from "react";
import prisma from "@/../../prisma/prisma-client";
import { notFound } from "next/navigation";
import Container from "@/components/Container/Container";

import ProductCardDetail from "@/components/ProductCardDetail/ProductCardDetail";
import { Metadata } from "next";
import Head from "next/head";

interface ProductIdProps {
  params: { id: string };
  searchParams: { [key: string]: string | string[] | undefined };
}

// export const metadata: Metadata = {
//   title: `Next14 Pizza | продукт ${product.name}`,
//   description: "Generated by create next app",
// };

export async function generateMetadata({ params }: { params: { id: string } }) {
  const product = await prisma.product.findUnique({
    where: {
      id: +params.id,
    },
  });
  if (!product) {
    return {
      title: `Next14 Pizza | продукт не найден`,
      description: "Generated by create next app",
    };
  }
  return {
    title: `Next14 Pizza | ${product.name}`,
    description: "Generated by create next app",
  };
}
const ProductId: FunctionComponent<ProductIdProps> = async ({
  params,
  searchParams,
}) => {
  const product = await prisma.product.findUnique({
    where: {
      id: +params.id,
    },
    include: {
      ingredients: true,
      items: true,
    },
  });
  if (!product) {
    return notFound();
  }


  return (
    <>
      <Container className={"flex flex-col my-20"}>
        <ProductCardDetail product={product} />
      </Container>
      {/* <div>карточка продукта {params.id}</div> */}

      {/* <pre>{JSON.stringify(product, null, 2)}</pre> */}

      {/* <script
        dangerouslySetInnerHTML={{
          __html: `
            //  window.scrollTo({ top: 1, left: 0, behavior: "auto" });
            //  window.scrollTo({ top: 1, left: 0, behavior: "instant" });
          `,
        }}
      /> */}
    </>
  );
};

export default ProductId;
