import LoginRegistration from "@/components/LoginRegistration/LoginRegistration";
import { Title } from "@/components/Title/Title";
import { JWT_TOKEN_NAME } from "@/constants/constants";
import { verifyTokenJWB } from "@/lib/utils";
import { Metadata } from "next";
import { cookies, headers } from "next/headers";
import { redirect, usePathname } from "next/navigation";
import { FunctionComponent, Suspense } from "react";
export const metadata: Metadata = {
  title: "Next14 Pizza | вход / регистрация",
  description: "Generated by create next app",
};
interface LoginPageProps {}

const LoginPage: FunctionComponent<LoginPageProps> = async () => {
  
  return (
    <>
      <div className="w-[800px] max-w-[100%] mx-auto my-7 p-5 text-center">
        <Title>Авторизация</Title>
      </div>
{/* <Suspense> */}
      <LoginRegistration></LoginRegistration>
      {/* </Suspense> */}
      <div className="mb-4"></div>
    </>
  );
};

export default LoginPage;
